### ISSUE TITLE
Bug: channelListMatcher URL has changed.

### ISSUE THREAD

**Issue by aixtools** [YuRaNnNzZZ/discord-message-relay-bot#1]
The string.match() was always returning null until I adjusted the match string

```
// var channelsListMatcher = /^(\d+)\?https:\/\/[\w\.]*discordapp.com\/api\/webhooks\/(\d+)\/([\w-]+)$/;
var channelsListMatcher = /^(\d+)\?https:\/\/[\w\.]*discord.com\/api\/webhooks\/(\d+)\/([\w-]+)$/;
```

**Comment by YuRaNnNzZZ** [comment]
Oh right, this was made before discord switched their domain for webhooks.
I'll change it to the new domain, thank you for the report!
